LANGUAGES = {
    "uz": {
        "welcome": "Assalomu alaykum! Jo'ja botiga xush kelibsiz! 🐓\n\n✨ <b>Interaktiv menyumizni sinab ko'ring!</b>\nSayt orqali qulay va tez buyurtma berishingiz mumkin.\n\nYoki pastdagi tugmalar orqali oddiy rejimda buyurtma bering 👇",
        "help": "❓ <b>Yordam bo'limi</b>\n\n• Buyurtma berish uchun pastdagi <b>'📦 Buyurtma berish'</b> yoki <b>'🛍 Interaktiv menyu'</b> tugmasini bosing.\n• Botni qayta ishga tushirish uchun /start yuboring.",
        "ask_name": "🤝 <b>Keling, tanishib olamiz!</b>\n\nIltimos, ismingizni kiriting:",
        "invalid_name": "⚠️ <b>Iltimos, ismingizni faqat matn ko'rinishida yuboring!</b>",
        "ask_store": "Yaxshi! 😊\n\nEndi do'koningiz nomini yozing:\n<i>(Masalan: Oila market)</i>",
        "invalid_store": "⚠️ <b>Iltimos, do'kon nomini faqat matn ko'rinishida yuboring!</b>",
        "select_product": "Ajoyib! Endi pastdagi ro'yxatdan mahsulotlarni tanlang (1-sahifa):",
        "ask_qty": "<b>{product}</b> uchun qancha miqdor buyurtma qilasiz (dona)?",
        "invalid_qty": "⚠️ <b>Iltimos, miqdorni to'g'ri yuboring!</b>",
        "cart_title": "🛒 <b>Sizning savatingiz:</b>\n\n",
        "cart_footer": "\nYana mahsulot qo'shasizmi yoki buyurtmani yakunlaysizmi?",
        "add_more": "Iltimos, keyingi mahsulotni tanlang:",
        "ask_location": "📍 Iltimos, do'koningiz geolokatsiyasini yuboring:",
        "invalid_location": "⚠️ <b>Iltimos, pastdagi tugma orqali geolokatsiyangizni yuboring!</b>",
        "ask_contact": "📱 Iltimos, pastdagi tugmani bosib telefon raqamingizni yuboring:",
        "invalid_contact": "⚠️ <b>Iltimos, pastdagi tugma orqali kontaktingizni yuboring!</b>",
        "checkout": "📋 <b>Buyurtmangizni tekshiring:</b>\n\n👤 Buyurtmachi: <b>{name}</b>\n🏪 Do'kon: <b>{store}</b>\n📦 Mahsulotlar:\n{products}\n📱 Telefon: {phone}\n📍 Geolokatsiya qabul qilindi!\n\nMa'lumotlar to'g'rimi?",
        "success": "Sizning buyurtmangiz muvaffaqiyatli qabul qilindi! ✅ Yaqin orada siz bilan bog'lanamiz.",
        "canceled": "Buyurtma bekor qilindi. ❌"
    },
    "ru": {
        "welcome": "Здравствуйте! Добро пожаловать в официальный бот Jo'ja! 🐓\n\n✨ <b>Попробуйте наше интерактивное меню!</b>\nВы можете удобно и быстро сделать заказ через сайт.\n\nИли используйте стандартные кнопки ниже 👇",
        "help": "❓ <b>Раздел помощи</b>\n\n• Для оформления заказа нажмите кнопку <b>'📦 Сделать заказ'</b> или <b>'🛍 Интерактивное меню'</b>.\n• Для перезапуска бота отправьте /start.",
        "ask_name": "🤝 <b>Давайте познакомимся!</b>\n\nПожалуйста, введите ваше имя:",
        "invalid_name": "⚠️ <b>Пожалуйста, отправьте ваше имя только в текстовом формате!</b>",
        "ask_store": "Отлично! 😊\n\nТеперь введите название вашего магазина:\n<i>(Например: Оила маркет)</i>",
        "invalid_store": "⚠️ <b>Пожалуйста, отправьте название магазина только в текстовом формате!</b>",
        "select_product": "Замечательно! Теперь выберите продукты из списка ниже (стр. 1):",
        "ask_qty": "Какое количество (в шт.) вы хотите заказать для <b>{product}</b>?",
        "invalid_qty": "⚠️ <b>Пожалуйста, отправьте количество корректно!</b>",
        "cart_title": "🛒 <b>Ваша корзина:</b>\n\n",
        "cart_footer": "\nХотите добавить ещё товар или завершить заказ?",
        "add_more": "Пожалуйста, выберите следующий товар:",
        "ask_location": "📍 Пожалуйста, отправьте геолокацию вашего магазина:",
        "invalid_location": "⚠️ <b>Пожалуйста, отправьте геолокацию с помощью кнопки ниже!</b>",
        "ask_contact": "📱 Пожалуйста, отправьте ваш номер телефона с помощью кнопки ниже:",
        "invalid_contact": "⚠️ <b>Пожалуйста, отправьте ваш контакт с помощью кнопки ниже!</b>",
        "checkout": "📋 <b>Проверьте ваш заказ:</b>\n\n👤 Заказчик: <b>{name}</b>\n🏪 Магазин: <b>{store}</b>\n📦 Товары:\n{products}\n📱 Телефон: {phone}\n📍 Геолокация получена!\n\nВсе данные верны?",
        "success": "Ваш заказ успешно принят! ✅ Скоро мы с вами свяжемся.",
        "canceled": "Заказ отменен. ❌"
    }
}