export const translations = {
  uz: {
    title: "JO'JA",
    subTitle: "Sifatli va Mazzali",
    all: "Barchasi",
    parts: "Qismlar 🍗",
    lotok: "Lotoklar 📥",
    naggets: "Naggetslar 🍟",
    marinade: "Marinat 🌶️",
    noImage: "Rasm yo'q",
    buyurtma: "Buyurtma berish",
    currency: "so'm",
    products: {
      "Boldir 🍗": "Boldir 🍗",
      "File 🥩": "File 🥩",
      "Maloe file 🥩": "Maloe file 🥩",
      "Son 🍖": "Son 🍖",
      "Qanot tirsak qismi 🪶": "Qanot tirsak qismi 🪶",
      "Qanot yelka qismi 🪶": "Qanot yelka qismi 🪶",
      "Achchiq qanot 🌶️": "Achchiq qanot 🌶️",
      "Baffalo 🌶️": "Баффало 🌶️",
      "Broyler 🐓": "Broyler 🐓",
      "Okorochka 10kg 📦": "Okorochka 10kg 📦",
      "Golen 10kg 📦": "Golen 10kg 📦",
      "Naggetslar Qarsillovchi ✨": "Naggetslar Qarsillovchi ✨",
      "Naggetslar Pishloqli 🧀": "Naggetslar Pishloqli 🧀",
      "Naggetslar Klassik 🍗": "Naggetslar Klassik 🍗",
      "Naggetslar Stripsi 🥢": "Naggetslar Stripsi 🥢",
      "Naggetslar Kids 👶": "Naggetslar Kids 👶",
      "Burger uchun kotletalar 🍔": "Burger uchun kotletalar 🍔",
      "Semeyniye kotletlari 🧆": "Semeyniye kotletlari 🧆",
      "Pishloqli va qaymoqli kotletlar 🧀": "Pishloqli va qaymoqli kotletlar 🧀",
      "Golen lotok 📥": "Boldir lotok 📥",
      "File lotok 📥": "File lotok 📥",
      "Son lotok 📥": "Son lotok 📥",
      "Maloe file lotok 📥": "Maloe file lotok 📥",
      "Jigar lotok 🩸": "Jigar lotok 🩸",
      "Yurak lotok ❤️": "Yurak lotok ❤️",
      "Oshqozon lotok 📥": "Oshqozon lotok 📥"
    },
    descriptions: {
      "Yumshoq va mazali tovuq go'shti mijozi uchun.": "Yumshoq va mazzali tovuq go'shti mijozi uchun.",
      "Tovuqning eng yumshoq va yog'siz ko'krak qismi.": "Tovuqning eng yumshoq va yog'siz ko'krak qismi.",
      "Sersuv va mazali son qismi, qovurish uchun juda mos.": "Sersuv va mazzali son qismi, qovurish uchun juda mos.",
      "Hamma yaxshi ko'radigan qarsildoq tovuq qanotchalari.": "Hamma yaxshi ko'radigan qarsildoq tovuq qanotchalari.",
      "Achchiq marinadlangan qanotlar, tayyor pishirish uchun.": "Achchiq marinadlangan qanotlar, tayyor pishirish uchun.",
      "Butun tovuq go'shti, pechda pishirishga tayyorlangan.": "Butun tovuq go'shti, pechda pishirishga tayyorlangan.",
      "O'ta qarsildoq non uvoqlariga belangan klassik naggetslar.": "O'ta qarsildoq non uvoqlariga belangan klassik naggetslar.",
      "Ichida erigan pishloqli qarsildoq issiq naggetslar.": "Ichida erigan pishloqli qarsildoq issiq naggetslar.",
      "An'anaviy usulda tayyorlangan oltinrang yumshoq naggetslar.": "An'anaviy usulda tayyorlangan oltinrang yumshoq naggetslar.",
      "Uzunchoq shakldagi qarsildoq tovuq stripslari.": "Uzunchoq shakldagi qarsildoq tovuq stripslari.",
      "Bolajonlar uchun maxsus tayyorlangan mazali va foydali naggetslar.": "Bolajonlar uchun maxsus tayyorlangan mazzali va foydali naggetslar.",
      "O'ta qarsildoq burger uchun tovuq kotletalari.": "O'ta qarsildoq burger uchun tovuq kotletalari.",
      "Mazali va sersuv oilaviy tovuq kotletalari.": "Mazali va sersuv oilaviy tovuq kotletalari.",
      "Ichida erigan pishloq va qaymoqli mazali kotletlar.": "Ichida erigan pishloq va qaymoqli mazali kotletlar.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq boldirlari.": "Maxsus gigiyenik lotokda qadoqlangan tovuq boldirlari.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq filesi.": "Maxsus gigiyenik lotokda qadoqlangan tovuq filesi.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq qanotlari.": "Maxsus gigiyenik lotokda qadoqlangan tovuq qanotlari.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq sonlari.": "Maxsus gigiyenik lotokda qadoqlangan tovuq sonlari."
    }
  },
  ru: {
    title: "JO'JA",
    subTitle: "Качественно и Вкусно",
    all: "Все",
    parts: "Части 🍗",
    lotok: "Лотки 📥",
    naggets: "Наггетсы 🍟",
    marinade: "Маринад 🌶️",
    noImage: "Нет фото",
    buyurtma: "Заказать",
    currency: "сум",
    products: {
      "Boldir 🍗": "Голень 🍗",
      "File 🥩": "Филе 🥩",
      "Maloe file 🥩": "Малое филе 🥩",
      "Son 🍖": "Бедро 🍖",
      "Qanot tirsak qismi 🪶": "Локтевая часть крыла 🪶",
      "Qanot yelka qismi 🪶": "Плечевая часть крыла 🪶",
      "Achchiq qanot 🌶️": "Крыло в остром маринаде 🌶️",
      "Baffalo 🌶️": "Баффало 🌶️",
      "Broyler 🐓": "Бройлер 🐓",
      "Okorochka 10kg 📦": "Окорочка 10кг 📦",
      "Golen 10kg 📦": "Голень 10кг 📦",
      "Naggetslar Qarsillovchi ✨": "Наггетсы Хрустящие ✨",
      "Naggetslar Pishloqli 🧀": "Наггетсы Сырные 🧀",
      "Naggetslar Klassik 🍗": "Наггетсы Классические 🍗",
      "Naggetslar Stripsi 🥢": "Стрипсы 🥢",
      "Naggetslar Kids 👶": "Наггетсы Кидс 👶",
      "Burger uchun kotletlar 🍔": "Котлеты для бургера 🍔",
      "Kotletlari Semeyniye 🧆": "Котлеты Семейные 🧆",
      "Kotletlari Pishloqli Slivochnie 🧀": "Котлеты Сливочные с сыром 🧀",
      "Golen lotok 📥": "Голень лоток 📥",
      "File lotok 📥": "Филе лоток 📥",
      "Bedro lotok 📥": "Бедро лоток 📥",
      "Son lotok 📥": "Бедро лоток 📥",
      "Maloe file lotok 📥": "Малое филе лоток 📥",
      "Jigar lotok 🩸": "Печень лоток 🩸",
      "Yurak lotok ❤️": "Сердце лоток ❤️",
      "Oshqozon lotok 📥": "Желудок лоток 📥"
    },
    descriptions: {
      "Yumshoq va mazali tovuq go'shti mijozi uchun.": "Нежное и вкусное куриное мясо.",
      "Tovuqning eng yumshoq va yog'siz ko'krak qismi.": "Мягкая и нежирная куриная грудка.",
      "Sersuv va mazali son qismi, qovurish uchun juda mos.": "Сочное бедро, отлично подходит для жарки.",
      "Hamma yaxshi ko'radigan qarsildoq tovuq qanotchalari.": "Вкусные хрустящие куриные крылышки.",
      "Achchiq marinadlangan qanotlar, tayyor pishirish uchun.": "Острые крылышки, готовые к запеканию.",
      "Butun tovuq go'shti, pechda pishirishga tayyorlangan.": "Целая тушка для запекания.",
      "O'ta qarsildoq non uvoqlariga belangan klassik naggetslar.": "Классические наггетсы в супер-хрустящей панировке.",
      "Ichida erigan pishloqli qarsildoq issiq naggetslar.": "Горячие хрустящие наггетсы с расплавленным сыром внутри.",
      "An'anaviy usulda tayyorlangan oltinrang yumshoq naggetslar.": "Золотистые нежные наггетсы, приготовленные по традиционному рецепту.",
      "Uzunchoq shakldagi qarsildoq tovuq stripslari.": "Хрустящие куриные стрипсы продолговатой формы.",
      "Bolajonlar uchun maxsus tayyorlangan mazali va foydali naggetslar.": "Вкусные и полезные наггетсы, приготовленные специально для детей.",
      "O'ta qarsildoq burger uchun tovuq kotletalari.": "Сочные котлеты в хрустящей панировке для бургера.",
      "Mazali va sersuv oilaviy tovuq kotletalari.": "Вкусные и сочные семейные куриные котлеты.",
      "Ichida erigan pishloq va qaymoqli mazali kotletlar.": "Нежные котлеты с начинкой из расплавленного сыра.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq boldirlari.": "Куриная голень, упакованная в специальный гигиенический лоток.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq filesi.": "Куриное филе, упакованное в специальный гигиенический лоток.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq qanotlari.": "Куриные крылышки, упакованные в специальный гигиенический лоток.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq sonlari.": "Куриное бедро, упакованное в специальный гигиенический лоток."
    }
  }
};  