export const translations = {
  uz: {
    title: "JO'JA",
    subTitle: "Sifatli va Mazzali",
    all: "Barchasi",
    parts: "Qismlar 🍗",
    lotok: "Lotoklar 📥",
    naggets: "Naggetslar 🍟",
    marinade: "Marinat 🌶️",
    noImage: "Rasm yo'q",
    buyurtma: "Buyurtma berish",
    currency: "so'm",
    products: {
      "Boldir 🍗": "Boldir 🍗",
      "File 🥩": "File 🥩",
      "Son 🍖": "Son 🍖",
      "Qanot 🪶": "Qanot 🪶",
      "Achchiq qanot 🌶️": "Achchiq qanot 🌶️",
      "Broyler 🐓": "Broyler 🐓",
      "Naggetslar Qarsillovchi ✨": "Naggetslar Qarsillovchi ✨",
      "Naggetslar Pishloqli 🧀": "Pishloqli naggetslar 🧀",
      "Naggetslar Klassik 🍗": "Klassik naggetslar 🍗",
      "Naggets Stripsi 🥢": "Stripslar 🥢",
      "Naggets Kids 👶": "Bolalar naggetsi 👶",
      "Golen lotok 📥": "Boldir lotok 📥",
      "File lotok 📥": "File lotok 📥",
      "Qanot lotok 📥": "Qanot lotok 📥",
      "Bedro lotok 📥": "Son lotok 📥"
    },
    descriptions: {
      "Yumshoq va mazali tovuq go'shti mijozi uchun.": "Yumshoq va mazzali tovuq go'shti mijozi uchun.",
      "Tovuqning eng yumshoq va yog'siz ko'krak qismi.": "Tovuqning eng yumshoq va yog'siz ko'krak qismi.",
      "Sersuv va mazali son qismi, qovurish uchun juda mos.": "Sersuv va mazzali son qismi, qovurish uchun juda mos.",
      "Hamma yaxshi ko'radigan qarsildoq tovuq qanotchalari.": "Hamma yaxshi ko'radigan qarsildoq tovuq qanotchalari.",
      "Achchiq marinadlangan qanotlar, tayyor pishirish uchun.": "Achchiq marinadlangan qanotlar, tayyor pishirish uchun.",
      "Butun tovuq go'shti, pechda pishirishga tayyorlangan.": "Butun tovuq go'shti, pechda pishirishga tayyorlangan.",
      "O'ta qarsildoq non uvoqlariga belangan klassik naggetslar.": "O'ta qarsildoq non uvoqlariga belangan klassik naggetslar.",
      "Ichida erigan pishloqli qarsildoq issiq naggetslar.": "Ichida erigan pishloqli qarsildoq issiq naggetslar.",
      "An'anaviy usulda tayyorlangan oltinrang yumshoq naggetslar.": "An'anaviy usulda tayyorlangan oltinrang yumshoq naggetslar.",
      "Uzunchoq shakldagi qarsildoq tovuq stripslari.": "Uzunchoq shakldagi qarsildoq tovuq stripslari.",
      "Bolajonlar uchun maxsus tayyorlangan mazali va foydali naggetslar.": "Bolajonlar uchun maxsus tayyorlangan mazzali va foydali naggetslar.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq boldirlari.": "Maxsus gigiyenik lotokda qadoqlangan tovuq boldirlari.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq filesi.": "Maxsus gigiyenik lotokda qadoqlangan tovuq filesi.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq qanotlari.": "Maxsus gigiyenik lotokda qadoqlangan tovuq qanotlari.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq sonlari.": "Maxsus gigiyenik lotokda qadoqlangan tovuq sonlari."
    }
  },
  ru: {
    title: "JO'JA",
    subTitle: "Качественно и Вкусно",
    all: "Все",
    parts: "Части 🍗",
    lotok: "Лотки 📥",
    naggets: "Наггетсы 🍟",
    marinade: "Маринад 🌶️",
    noImage: "Нет фото",
    buyurtma: "Заказать",
    currency: "сум",
    products: {
      "Boldir 🍗": "Голень 🍗",
      "File 🥩": "Филе 🥩",
      "Son 🍖": "Бедро 🍖",
      "Qanot 🪶": "Крыло 🪶",
      "Achchiq qanot 🌶️": "Крыло в остром маринаде 🌶️",
      "Broyler 🐓": "Бройлер 🐓",
      "Naggetslar Qarsillovchi ✨": "Наггетсы Хрустящие ✨",
      "Naggetslar Pishloqli 🧀": "Сырные наггетсы 🧀",
      "Naggetslar Klassik 🍗": "Классические наггетсы 🍗",
      "Naggets Stripsi 🥢": "Стрипсы 🥢",
      "Naggets Kids 👶": "Детские наггетсы 👶",
      "Golen lotok 📥": "Голень в лотке 📥",
      "File lotok 📥": "Филе в лотке 📥",
      "Qanot lotok 📥": "Крылья в лотке 📥",
      "Bedro lotok 📥": "Бедро в лотке 📥"
    },
    descriptions: {
      "Yumshoq va mazali tovuq go'shti mijozi uchun.": "Нежное и вкусное куриное мясо.",
      "Tovuqning eng yumshoq va yog'siz ko'krak qismi.": "Мягкая и нежирная куриная грудка.",
      "Sersuv va mazali son qismi, qovurish uchun juda mos.": "Сочное бедро, отлично подходит для жарки.",
      "Hamma yaxshi ko'radigan qarsildoq tovuq qanotchalari.": "Вкусные хрустящие куриные крылышки.",
      "Achchiq marinadlangan qanotlar, tayyor pishirish uchun.": "Острые крылышки, готовые к запеканию.",
      "Butun tovuq go'shti, pechda pishirishga tayyorlangan.": "Целая тушка для запекания.",
      "O'ta qarsildoq non uvoqlariga belangan klassik naggetslar.": "Классические наггетсы в супер-хрустящей панировке.",
      "Ichida erigan pishloqli qarsildoq issiq naggetslar.": "Горячие хрустящие наггетсы с расплавленным сыром внутри.",
      "An'anaviy usulda tayyorlangan oltinrang yumshoq naggetslar.": "Золотистые нежные наггетсы, приготовленные по традиционному рецепту.",
      "Uzunchoq shakldagi qarsildoq tovuq stripslari.": "Хрустящие куриные стрипсы продолговатой формы.",
      "Bolajonlar uchun maxsus tayyorlangan mazali va foydali naggetslar.": "Вкусные и полезные наггетсы, приготовленные специально для детей.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq boldirlari.": "Куриная голень, упакованная в специальный гигиенический лоток.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq filesi.": "Куриное филе, упакованное в специальный гигиенический лоток.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq qanotlari.": "Куриные крылышки, упакованные в специальный гигиенический лоток.",
      "Maxsus gigiyenik lotokda qadoqlangan tovuq sonlari.": "Куриное бедро, упакованное в специальный гигиенический лоток."
    }
  }
};